name       : python-pmw
version    : 2.0.0
release    : 1
source     :
    - https://downloads.sourceforge.net/project/pmw/Pmw-2.0.0.tar.gz : 2babb2855feaabeea1003c6908b61c9d39cff606d418685f0559952714c680bb
license    : BSD-2-Clause
component  : programming.python
summary    : Python Mega Widgets (Pmw) is a toolkit for building high-level compound widgets in Python using the Tkinter module. 
description: |
    Pmw is a toolkit for building high-level compound widgets, or megawidgets,
    constructed using other widgets as component parts. It promotes consistent look and feel within
    and between graphical applications, is highly configurable to your needs and is easy to use.
setup      : |
    %python_setup
install    : |
    %python_install
